before:
  hooks:
    - go mod tidy
    - go run ./cmd/gen-docs

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    main: ./cmd/keepalive
    binary: keepalive
    ldflags:
      - -s -w -X main.version={{.Version}}
    mod_timestamp: '{{ .CommitTimestamp }}'

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - docs/completions/**
      - man/keepalive.1
    format_overrides:
      - goos: windows
        format: zip

checksum: {}

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'

release:
  github:
    owner: stigoleg
    name: keep-alive
  replace_existing_artifacts: true

brews:
  - name: keepalive
    description: A lightweight, cross-platform utility to prevent system sleep
    homepage: https://github.com/stigoleg/keep-alive
    license: MIT
    repository:
      owner: stigoleg
      name: homebrew-tap
      token: '{{ .Env.GH_PAT }}'
    directory: Formula
    commit_author:
      name: GoReleaser Bot
      email: bot@goreleaser.com
    install: |
      bin.install "keepalive"
    skip_upload: '{{ not (isEnvSet "PUBLISH_PACKAGE_MANAGERS") }}'

scoops:
  - name: keepalive
    description: A lightweight, cross-platform utility to prevent system sleep
    homepage: https://github.com/stigoleg/keep-alive
    license: MIT
    repository:
      owner: stigoleg
      name: scoop-bucket
      token: '{{ .Env.GH_PAT }}'
    skip_upload: '{{ not (isEnvSet "PUBLISH_PACKAGE_MANAGERS") }}'

notarize:
  macos:
    - enabled: '{{ isEnvSet "MACOS_SIGN_P12" }}'
      sign:
        certificate: '{{ .Env.MACOS_SIGN_P12 }}'
        password: '{{ .Env.MACOS_SIGN_PASSWORD }}'
      notarize:
        issuer_id: '{{ .Env.MACOS_NOTARY_ISSUER_ID }}'
        key_id: '{{ .Env.MACOS_NOTARY_KEY_ID }}'
        key: '{{ .Env.MACOS_NOTARY_KEY }}'
        wait: true
        timeout: 20m
