// Package service installs keepalive as a per-user login service: a launchd
// LaunchAgent on macOS, a systemd --user unit on Linux (an XDG autostart entry
// when systemd is not reachable) and a Task Scheduler logon task on Windows.
// The service runs "<exe> --plain <args…>" with KEEPALIVE_ORIGIN=service where
// the format allows setting the environment.
//
// The file formats are generated by plain functions and every external
// command goes through a runner, so tests never touch the real system.
package service

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"time"
)

const (
	// Label is the launchd job label.
	Label = "io.github.stigoleg.keepalive"
	// UnitName is the systemd --user unit.
	UnitName = "keepalive.service"
	// DesktopName is the XDG autostart entry.
	DesktopName = "keepalive.desktop"
	// TaskName is the Task Scheduler task.
	TaskName = "keepalive"

	// OriginEnv and OriginValue mark a process started by the service; they
	// match ipc.EnvOrigin and ipc.OriginService.
	OriginEnv   = "KEEPALIVE_ORIGIN"
	OriginValue = "service"

	// CommandTimeout bounds every external command.
	CommandTimeout = 15 * time.Second
)

// ErrNotInstalled is returned by Uninstall when there is nothing to remove.
var ErrNotInstalled = errors.New("the keepalive service is not installed")

// Spec is what the service runs. LogPath receives stdout and stderr where the
// service manager supports it (launchd); systemd logs to the journal.
type Spec struct {
	Executable string
	Args       []string // session flags; "--plain" is prepended
	LogPath    string
}

// State describes the installed service.
type State struct {
	Installed bool
	Running   bool
	Detail    string // human summary, e.g. "running (pid 123)"
	Path      string // plist or unit/desktop file, or the task name
	// Restarts counts restarts after a failed exit since the service was
	// loaded, where the manager reports it (launchd, systemd); 0 otherwise.
	Restarts int
}

// Manager installs, removes and inspects the service.
type Manager interface {
	Install(Spec) error
	Uninstall() error
	Status() (State, error)
	Name() string
}

// New returns the Manager for this operating system.
func New() (Manager, error) { return newManager() }

// programArgs is the full argument list after the executable.
func (s Spec) programArgs() []string { return append([]string{"--plain"}, s.Args...) }

func (s Spec) validate(isAbs func(string) bool) error {
	if s.Executable == "" {
		return errors.New("service: no executable")
	}
	if !isAbs(s.Executable) {
		return fmt.Errorf("service: executable %q is not an absolute path", s.Executable)
	}
	for _, v := range append([]string{s.Executable, s.LogPath}, s.Args...) {
		if strings.ContainsRune(v, 0) {
			return fmt.Errorf("service: %q contains a NUL byte", v)
		}
	}
	return nil
}

func unixAbs(p string) bool { return strings.HasPrefix(p, "/") }

func windowsAbs(p string) bool {
	if strings.HasPrefix(p, `\\`) {
		return true
	}
	return len(p) >= 3 && p[1] == ':' && (p[2] == '\\' || p[2] == '/')
}

// CommandError is an external command that failed. Hint, when set, suggests
// what to do next; it is not part of Error().
type CommandError struct {
	Command string // command line, for messages
	Stderr  string
	Err     error
	Hint    string
}

func (e *CommandError) Error() string {
	msg := e.Command + ": " + e.Err.Error()
	if e.Stderr != "" {
		msg += ": " + e.Stderr
	}
	return msg
}

func (e *CommandError) Unwrap() error { return e.Err }

func (e *CommandError) ErrorHint() string { return e.Hint }

type hintError struct {
	msg, hint string
}

func (e *hintError) Error() string     { return e.msg }
func (e *hintError) ErrorHint() string { return e.hint }

// Hint returns the hint attached to err, or "".
func Hint(err error) string {
	var h interface{ ErrorHint() string }
	if errors.As(err, &h) {
		return h.ErrorHint()
	}
	return ""
}

// hinted attaches hint to a CommandError that has none.
func hinted(err error, hint string) error {
	var ce *CommandError
	if errors.As(err, &ce) && ce.Hint == "" {
		ce.Hint = hint
	}
	return err
}

// runner runs an external command and returns its stdout. On failure the
// stdout is still returned (systemctl is-active reports through it).
type runner interface {
	Run(name string, args ...string) ([]byte, error)
}

type execRunner struct{ timeout time.Duration }

func (r execRunner) Run(name string, args ...string) ([]byte, error) {
	ctx, cancel := context.WithTimeout(context.Background(), r.timeout)
	defer cancel()
	cmd := exec.CommandContext(ctx, name, args...)
	cmd.SysProcAttr = sysProcAttr()
	cmd.WaitDelay = time.Second
	var stdout, stderr bytes.Buffer
	cmd.Stdout, cmd.Stderr = &stdout, &stderr
	err := cmd.Run()
	if err == nil {
		return stdout.Bytes(), nil
	}
	if ctx.Err() == context.DeadlineExceeded {
		err = fmt.Errorf("timed out after %s", r.timeout)
	}
	return stdout.Bytes(), &CommandError{
		Command: strings.Join(append([]string{name}, args...), " "),
		Stderr:  strings.TrimSpace(stderr.String()),
		Err:     err,
	}
}

// writeFile replaces path atomically.
func writeFile(path string, data []byte, perm os.FileMode) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("service: %w", err)
	}
	f, err := os.CreateTemp(filepath.Dir(path), "."+filepath.Base(path)+".*")
	if err != nil {
		return fmt.Errorf("service: %w", err)
	}
	defer os.Remove(f.Name())
	_, err = f.Write(data)
	if err == nil {
		err = f.Chmod(perm)
	}
	if cerr := f.Close(); err == nil {
		err = cerr
	}
	if err == nil {
		err = os.Rename(f.Name(), path)
	}
	if err != nil {
		return fmt.Errorf("service: write %s: %w", path, err)
	}
	return nil
}

func exists(path string) bool {
	_, err := os.Stat(path)
	return err == nil
}

// removeIfExists removes path, ignoring a missing file.
func removeIfExists(path string) error {
	if err := os.Remove(path); err != nil && !errors.Is(err, os.ErrNotExist) {
		return fmt.Errorf("service: %w", err)
	}
	return nil
}

// ResolveExecutable returns the path the service should run, preferring a
// stable one: when the "keepalive" found on PATH is this same binary (for
// example Homebrew's /opt/homebrew/bin symlink into a versioned Cellar
// directory), the PATH entry is used so upgrades keep working. Temporary
// builds (go run, go test, anything under the temp dir) are refused. On
// Windows keepalivew.exe next to the binary is preferred; without it the
// warning says a console window will show.
func ResolveExecutable() (path, warning string, err error) {
	return resolveExecutable(exeEnv{
		executable:   os.Executable,
		lookPath:     exec.LookPath,
		evalSymlinks: filepath.EvalSymlinks,
		exists:       exists,
		tempDir:      os.TempDir(),
		goos:         runtime.GOOS,
	})
}

type exeEnv struct {
	executable   func() (string, error)
	lookPath     func(string) (string, error)
	evalSymlinks func(string) (string, error)
	exists       func(string) bool
	tempDir      string
	goos         string
}

func resolveExecutable(env exeEnv) (string, string, error) {
	exe, err := env.executable()
	if err != nil {
		return "", "", fmt.Errorf("service: locate the keepalive binary: %w", err)
	}
	exe = filepath.Clean(exe)
	resolve := func(p string) string {
		if r, err := env.evalSymlinks(p); err == nil {
			return r
		}
		return p
	}
	real := resolve(exe)
	if temporary(exe, env.tempDir) || temporary(real, env.tempDir) || temporary(real, resolve(env.tempDir)) {
		return "", "", &hintError{
			msg:  fmt.Sprintf("service: %s is a temporary build (go run, go test or the temp directory)", real),
			hint: `install keepalive first (for example "go install ./cmd/keepalive" or a release package) and run "keepalive service install" from the installed binary`,
		}
	}
	chosen := exe
	if lp, err := env.lookPath("keepalive"); err == nil {
		if abs, err := filepath.Abs(lp); err == nil && resolve(abs) == real {
			chosen = abs
		}
	}
	if env.goos == "windows" {
		w := filepath.Join(filepath.Dir(chosen), "keepalivew.exe")
		if env.exists(w) {
			return w, "", nil
		}
		return chosen, "keepalivew.exe was not found next to " + filepath.Base(chosen) + "; the service will open a console window at logon", nil
	}
	return chosen, "", nil
}

// temporary reports a path under dir or inside a go-build directory.
func temporary(p, dir string) bool {
	for _, part := range strings.Split(filepath.ToSlash(p), "/") {
		if strings.HasPrefix(part, "go-build") {
			return true
		}
	}
	if dir == "" {
		return false
	}
	rel, err := filepath.Rel(dir, p)
	return err == nil && rel != ".." && !strings.HasPrefix(rel, ".."+string(filepath.Separator)) && !filepath.IsAbs(rel)
}
